---
title: "fdas"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{=tex}
\begin{equation}
  \tilde{y}_h={SG}\hat{y}_h,
  \tag{11.7}
\end{equation}
```
This equation as discussed above shows that *SG* will return a set of
coherent forecasts.

Traditional Methods include the base forecasts from a single level of
aggregation which can be considered as usage of limited information. n

However we need to optimize all the G matrices such that when *SG*
combines and reconciles all the base forecasts in order to produce
coherent forecasts.

## The MinT optimal reconciliation approach

This is a way to find a *G* matrix which minimizes the total forecast
variance of the set of coherent forecasts, leading to the MinT (Minimum
Trace) optimal reconciliation approach.

Before, performing any steps ahead, we need to make sure that we have
unbiased forecasts.

If $\tilde{y}_h$ is unbiased then $\hat{y}_h$ is unbiased provided
{SGS}={S}

IMPORTANT: No top-down method satisfies this constraint, so all top-down
approaches result in biased coherent forecasts.

Finding errors: variance-covariance matrix of the h-step-ahead coherent
forecast errors is given by

```{=tex}
\begin{equation*}
{V}_h = \text{Var}[{y}_{T+h}-\tilde{{y}}_h]={SGW}_h{G}'{S}'
\end{equation*}
```
where ${W}_h=\text{Var}[({y}_{T+h}-\hat{{y}}_h)]$ is the
variance-covariance matrix of the corresponding base forecast errors.\
The objective is to find a matrix *G* that minimizes the error variances
of the coherent forecasts. These error variances are on the diagonal of
the matrix ${V}_h$ , and so the sum of all the error variances is given
by the trace of the matrix ${V}_h$.

The equation below shows that matrix *G* which minimizes the trace of
${V}_h$ such that ${SGS}=S$ , is given by

$${G}=({S}'{W}_h^{-1}{S})^{-1}{S}'{W}_h^{-1}$$

Therefore, the optimally reconciled forecasts are given by

```{=tex}
\begin{equation}
\tag{11.8}
  \tilde{{y}}_h={S}({S}'{W}_h^{-1}{S})^{-1}{S}'{W}_h^{-1}\hat{{y}}_h
\end{equation}
```
MinT is implemented by min_trace() within the reconcile() function.\
We need to estimate ${W}_h$, the forecast error variance of the
h-step-ahead base forecasts. This can be difficult, and so we provide
four simplifying approximations that have been shown to work well in
both simulations and in practice. Lets four simplifying approximations
that have been shown to work well in both simulations and in practice.

1.  Set ${W}_h=k_h{I}$ for all h, where $k_h > 0$. This is the most
    simplifying assumption to make, and means that G is independent of
    the data, providing substantial computational savings. The
    disadvantage, however, is that this specification does not account
    for the differences in scale between the levels of the structure, or
    for relationships between series.

    Setting ${W}_h=k_h{I}$ in gives the ordinary least squares (OLS)
    estimator we introduced in with ${X}={S}$ and ${y}=\hat{y}$. Hence
    this approach is usually referred to as OLS reconciliation. It is
    implemented in min_trace() by setting method = "ols".

2.  Set ${W}_{h} = k_h\text{diag}(\hat{{W}}_{1})$ for all h, where
    $k_{h}> 0$,

    $$\hat{{W}}_{1} = \frac{1}{T}\sum{{e}_{t}{e_t}}'$$

    and ${e}_{t}$ is an n-dimensional vector of residuals of the models
    that generated the base forecasts stacked in the same order as the
    data. It referred as WLS (weighted least squares) estimator using
    variance scaling beacuase this specification scales the base
    forecasts using the variance of the residuals. The approach is
    implemented in min_trace() by setting method = "wls_var".

3.  Set ${W}_{h}=k_{h}{\Lambda}$ for all h, where $k_{h} > 0$,
    ${\Lambda}=\text{diag}({S}{1})$, and 1 is a unit vector of dimension
    m(the number of bottom-level series). It is referred to as
    structural scaling because this estimator only depends on the
    structure of the aggregations, and not on the actual data. The
    approach is implemented in min_trace() by setting method =
    "wls_struct".

4.  Set ${W}_h = k_h {W}_1$ for all h, where $k_{h} > 0$ Here we only
    assume that the error covariance matrices are proportional to each
    other, and we directly estimate the full one-step covariance matrix
    ${W}_1$. The most obvious and simple way would be to use the sample
    covariance. This is implemented in min_trace() by setting method =
    "mint_cov".

However, for cases where the number of bottom-level series m is large
compared to the length of the series T , this is not a good estimator.
Instead we use a shrinkage estimator which shrinks the sample covariance
to a diagonal matrix. This is implemented in min_trace() by setting
method = "mint_shrink".

The best reconciliation projections are produced using all the data
available inside a hierarchical or grouped framework, unlike any other
existing method. This is crucial because some aggregation levels or
groupings may highlight data characteristics that are interesting to the
user and crucial for modelling.
